---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "many_pods.fullname" . }}
  labels:
    app: {{ template "many_pods.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
data:
  VAL1: "{{ .Values.many_pods.val1 }}"
