apiVersion: v1
kind: Secret
metadata:
  name: {{ template "many_pods.fullname" . }}
  labels:
    app: {{ template "many_pods.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
type: Opaque
data:
  SEC_VAL1: {{ index .Values "many_pods.secVal1" }}
